services:
  servier:
    container_name: allocab-server
    build:
      context: .
      dockerfile: Dockerfile
    image: allocab-server:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/allocab-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zozmgaming
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:latest
    container_name: allocab-db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    # or set shared memory limit when deploy via swarm stack
    # volumes:
    #  - type: tmpfs
    #  - postgres-data: /var/lib/postgresql/data
    # target: /dev/shm
    # tmpfs:
    #   size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: allocab-db
      POSTGRES_PASSWORD: zozmgaming
      POSTGRES_USER: postgres
